version: '3.8'

services:
  stockly-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: stockly-dev
    volumes:
      - .:/app
    restart: unless-stopped
